[package]
name = "MikuMikuLoader"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
serde = "1.0.219"
toml = "0.8.22"
sekai_injector = { path = "/home/pretty/projects/ProjectSekai-Repacked/sekai-injector" }
colored = "3.0.0"
tokio = "1.45.0"
axum = "0.8.4"
axum-server = "0.7.2"
tower-http = { version = "0.6.4", features = ["fs"] }
hyper-rustls = "0.27.5"
hyper-util = "0.1.11"
serde_json = "1.0.140"
