name: build

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            bin: MikuMikuLoader-linux-amd64
          - os_name: Windows-x86_64
            target: x86_64-pc-windows-msvc
            bin: MikuMikuLoader-amd64.exe
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Build binary with cross
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true

      - name: Rename binary (Linux)
        run: mv target/${{ matrix.platform.target }}/release/MikuMikuLoader target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: matrix.platform.os_name == 'Linux-x86_64'

      - name: Rename binary (Windows)
        run: mv target/${{ matrix.platform.target }}/release/MikuMikuLoader target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: matrix.platform.os_name == 'Windows-x86_64'

      - name: Generate SHA-256
        run: |
          FILE=target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          shasum -a 256 "$FILE" | cut -d ' ' -f 1 > "$FILE.sha256"

      - name: Upload binary and SHA-256 checksum as build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}-artifacts
          path: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
